// Code generated by go-swagger; DO NOT EDIT.
//
// Copyright NetFoundry Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

// Package rest_client_api_server Ziti Edge Client
//
//	Hanzo ZT Edge Client API
//	Schemes:
//	  https
//	Host: demo.zt.dev
//	BasePath: /edge/client/v1
//	Version: 0.26.53
//	License: Apache 2.0 https://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: Hanzo ZT<help@hanzozt.dev> https://hanzozt.discourse.group
//
//	Consumes:
//	  - application/pkcs7
//	  - application/x-pem-file
//	  - application/json
//	  - text/plain
//
//	Produces:
//	  - application/pkcs7-mime
//	  - image/png
//	  - application/json
//	  - text/yaml
//
// swagger:meta
package rest_client_api_server
